### ISSUE TITLE
Classes not building without certain values

### ISSUE THREAD

**Issue by biancamacias** [googleinterns/univiz#125]
Currently, CollegeScorecard API includes many colleges and institutions, including trade schools or professional studies schools. Many of these schools don't include SAT scores or admission rates. This in turn causes the colleges to not build the `ScorecardData` objects, which means the back-end is not able to communicate the necessary data elements to the front-end. 

`ScorecardData` class should have either optional or default parameters.

![image](https://user-images.githubusercontent.com/51244558/91593091-65842c00-e914-11ea-8b78-44b072b68de5.png)

**Comment by kaveh096** [comment]
An attempt as made to load a university that does not have those fields: http://screen/D8tkVjN7txajXer
