### ISSUE TITLE
Get the mvn deploy target up and running.

### ISSUE THREAD

**Issue by ccondit** [googleinterns/univiz#27]
We might be able to use the portfolio projects as a template.

**Comment by kaveh096** [comment]
- [ ] First make the `mvn deploy` work. Add needed configs.
- [ ] Consider making deploy automatically. Here are some resources:

- http://cloud/cloud-build/docs/building/build-java
- http://cloud/cloud-build/docs/automating-builds/create-manage-triggers#console
- http://cloud/functions/docs/deploying/repo
- http://cloud/source-repositories/docs/quickstart-triggering-builds-with-source-repositories
- https://github.com/googleinterns/step7-2020/blob/master/cloudbuild.yaml
- https://medium.com/swlh/deploying-github-repository-to-google-cloud-platform-997d296547e6

**Comment by kaveh096** [comment]
I also need to change the version to a standard gcloud format. I'm getting the following error:

```bash
 GCLOUD: ERROR: (gcloud.app.deploy) argument --version/-v: Bad value [1.0-SNAPSHOT]: May only contain lowercase letters, digits, and hyphens. Must begin and end with a letter or digit. Must not exceed 63 characters.
```

**Comment by kaveh096** [comment]
Given we have API_KEY files that are not present in the repo, i'm not sure how would the automatic deployment would work. At this point, i believe it's not a priority.
